### ISSUE TITLE
Simple algorithms

### ISSUE THREAD

**Issue by Matricarin** [Matricarin/Workshop.BasicOfProgramming#1]
### Tasks from the first workshop.

- [ ] **Expr1.** Как поменять местами значения двух переменных? Можно ли это сделать без ещё одной временной переменной. Стоит ли так делать?
- [ ] **Expr2.** Задается натуральное трехзначное число (гарантируется, что трехзначное). Развернуть его, т.е. получить трехзначное число, записанное теми же цифрами в обратном порядке.
- [ ] **Expr3.** Задано время Н часов (ровно). Вычислить угол в градусах между часовой и минутной стрелками. Например, 5 часов -> 150 градусов, 20 часов -> 120 градусов. Не использовать циклы.
- [ ] **Expr4.** Найти количество чисел меньших N, которые имеют простые делители X или Y.
- [ ] **Expr5.** Найти количество високосных лет на отрезке [a, b] не используя циклы.
- [ ] **Expr6.** Посчитать расстояние от точки до прямой, заданной двумя разными точками.
- [ ]  **Expr7.** Найти вектор, параллельный прямой. Перпендикулярный прямой. Прямая задана коэффициентами уравнения прямой. 
- [ ] **Expr8.** Дана прямая L и точка A. Найти точку пересечения прямой L с перпендикулярной ей прямой P, проходящей через точку A. Можете считать, что прямая задана либо двумя точками, либо коэффициентами уравнения прямой — как вам удобнее.
